import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import AuthHydration from "./providers/AuthHydration";


export const metadata: Metadata = {
  title: "Activity Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <AuthHydration />
          {children}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
